[tool]
id = "com.dailyhobbyist.stopwatch"
label = "Stopwatch"
versionCode = 10
versionName = "5.3.1"
permissions = []
# change to com.thelightphone.sdk.emulator if you run in the SDK emulator
serverPackage = "com.lightos"
