[tool]
id = "com.dailyhobbyist.stopwatch"
label = "Stopwatch"
versionCode = 7
versionName = "5.1.1"
permissions = []
# change to com.thelightphone.sdk.emulator if you run in the SDK emulator
serverPackage = "com.lightos"
